---
- name: Upload website tarball
  copy:
    src: /path/to/website.tar.gz
    dest: /tmp/website.tar.gz

- name: Extract website
  unarchive:
    src: /tmp/website.tar.gz
    dest: /var/www/html
    remote_src: yes