---
- name: Copy compressed site
  ansible.builtin.copy:
    src: /Users/samallen/Code/Projects/devops-roadmap/configuration-management/site.tar.gz
    dest: /tmp/site.tar.gz
    mode: preserve

- name: Ensure directory exists
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  become: true

- name: Uncompress site
  ansible.builtin.unarchive:
    src: /tmp/site.tar.gz
    dest: /var/www/html
    remote_src: true
  become: true
