---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install apt updates
  ansible.builtin.apt:
    upgrade: safe
  become: true

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  become: true

- name: Allow ssh through ufw
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp
  become: true

- name: Allow http through ufw
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp
  become: true

- name: Allow ssh through ufw
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp
  become: true

- name: Block default incoming through ufw
  community.general.ufw:
    default: deny
    direction: incoming
  become: true

- name: Enable ufw
  community.general.ufw:
    state: enabled
  become: true
